### ISSUE TITLE
Failure to build imported site

### ISSUE THREAD

**Issue by pallan** [CloudCannon/cloudcannon-jekyll#1]
I am importing a site from Gitlab and its failing to build in CloudCannon.  The error during the build is as below.

```
Configuration file: action-sunglasses.cloudvent.net/_config.yml
            Source: action-sunglasses.cloudvent.net
       Destination: _site
 Incremental build: disabled. Enable with --incremental
      Generating... 
Liquid Exception: Liquid error (line 10): undefined method env in _cloudcannon/details.json
------------------------------------------------
Jekyll 4.0.0   Please append `--trace` to the `build` command 
for any additional information or backtrace. 
------------------------------------------------
Reading build output... failed
There was an issue parsing the build details. Usually caused by:
 - Front matter missing space before value if value has colon
   i.e. key:"da: ta" instead of key: "da: ta"
```

If I generate at site from a template everything works its only on imported sites.  Local builds are fine, if I try to include this gem locally I get the same error

**Comment by rphillips-nz** [comment]
Looks like it is failing on line 10: `"environment": {{ jekyll.env | jsonify }},`, specifically `jekyll.env`. To my knowledge, that should be available in any Jekyll build. Do you have a reproducible test case, or is the repo public? If not, it's probably faster to get in touch with support in the CloudCannon app.
